config/routes.rb
Rails.application.routes.draw do
root "homes#top"
get "/homes/about" => "homes#about", as: "about"

devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# scope module: :public do
#   get '/searches/search' => 'searches#search'
#   get '/posts/rank' => 'posts#rank'
#   get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: 'confirm_withdraw'
#   patch '/users/withdraw' => 'users#withdraw'
#   get 'genres/:id/genre_rank' => 'genres#genre_rank', as: 'genre_rank'
#   resources :genres, only: [:show]
#   resources :users, only: [:show, :edit,:update]
#   resource :posts, only: [:new,:create]
#   resources :posts, only: [:show,:index,:destroy,:edit,:update] do
#     resource :favorites, only: [:create, :destroy]
#     resources :comments, only: [:create,:destroy,:new]
#   end
# end

scope module: :public do
  get '/searches/search' => 'searches#search'
  resources :genres, only: [:show] do
    member do 
      get 'genre_rank'
    end
  end
  resources :users, only: [:show,:edit,:update] do
    collection do 
      get 'confirm_withdraw'
      patch 'withdraw'
    end
  end
  resources :posts do
    collection do
      get 'rank'
    end
    resources :comments, only: [:create,:destroy,:new]
    resource :favorites, only: [:create, :destroy]
  end
end

namespace :admin do
  resources :posts, only: [:destroy,:show]
    resources :comments, only: [:destroy]
  resources :users, only: [:show,:index,:edit,:update,:destroy]
  patch '/users/withdraw' => 'users#withdraw'
  get 'users/:id/comment_index' => 'users#comment_index'
  resources :genres, only: [:index, :show, :edit, :create, :update]

end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @posts = Post.post_rank
    @genres = Genre.all
  end
  
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<h1>about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<%= stylesheet_link_tag '_footer' %>
<%= stylesheet_link_tag 'homes' %>
<div class= "container">
    <%= flash[:notice] %>
  <div class="main-image row">
    <div class="intensifies col d-flex justify-content-center align-items-center">
        <h1>　テキスト通りに</br>
          　やったんですけどネ💢
        </h1>
    </div>
  </div>

  <div class="row">
    <div class="main-text col-10 offset-2 mb-2">
    
    <p>〜Text番付へようこそ〜</p>

    <p>テキスト通りにやったのになんででけへんねん！！</p>
    <p>
    <p>プログラミング初学者の方は一度は経験したことかと思います。
    <p>学習を進めていくと、テキストを丸写ししたからできるなんてそんな甘いものではないな。</p>
    <p>と、気づいていくものですが。</p>

    <p>そういう初学者の方へ寄り添いたい、最初のテキストはわかりやすいものを手に取って欲しい。</p>
    <p>そんな想いで初学者向けのテキストを使用者の皆さんの評価順にランキングにしました。</p>

    <p>だから優しいピンクとベージュのカラーリングなわけです。ちょっとでも心が軽くなるように。</p>
    </div>
  </div>
  
  <h2>全テキストのRanking</h2>
  <div class="box1-5">
    <span class="box-title1-5">※下記のタグでジャンルごとのランキングが確認できます。</span>
    <ul class="genre-list">
      <% @genres.each do |genre| %>
        <li class="genre-item">
          <%= link_to genre.genre_name, genre_rank_genre_path(genre.id) %>
        </li>
      <% end %>
    </ul>
  </div>
  
    <% @posts.each.with_index(1) do |post, i| %>
    <div class="row">
    <div class="col text-center">
      <% if i == 1 %>
        <div class="first-place"></div>
      <% elsif i == 2 %>
        <div class="second-place"></div>
      <% else %>
        <div class="third-place"></div>
      <% end %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-3">
      <p>投稿者名：<%= post.user.name %>さん</p>
      <%= link_to post_path(post.id) do %>
        <%= image_tag post.get_image(250, 250) %>
      <% end %>
      <P><%= link_to "テキストの詳細をチェック", post_path(post.id) %></P>
    </div>
    <div class="box col-6">
      
      <div class="post-title">
        <%= post.text_name %>
      </div>
      
      <p>投稿日：<%= post.created_at.strftime('%Y/%m/%d') %>　　価格：<%= post.price %>円　　ジャンル:<%= post.genre.genre_name %></p>
      <p>
        商品説明：<br><%= truncate(post.introduction, length: 120) do %>
            (続きは<%= link_to '詳細', post_path(post) %>をクリック。）
            <% end %>
      </p>
      <p>
        投稿者レビュー：<br><%= truncate(post.review, length: 100) do %>
            (続きは<%= link_to '詳細', post_path(post) %>をクリック。）
            <% end %>
      </p>
    </div>

    <div class="col-3 text-center">
      <h4><%= 'みんなの評価' %></h4></br>
      <%= '総合評価' %><%= post.comments.average(:total_score).to_f.round(1) %>
        <div id="post_raty_<%= post.id %>" data-score="<%= post.comments.average(:total_score).to_f.round(1) %>"></div>
        <script>
              // scriptファイルをどのidの部分に配置するかを指定
        raty(document.querySelector('#post_raty_<%= post.id %>'),
            {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              score: <%= post.comments.average(:total_score).to_f.round(1) %>,
              readOnly: true,
              half: true,
        //星画像の指定などのオプションをここに記述,
            }
        );
        </script>

        <%= '読みやすさ' %>
        <div id="read_score_raty_<%= post.id %>" data-score="<%= post.comments.average(:read_score).to_f.round(1) %>"></div>
        <script>
          // scriptファイルをどのidの部分に配置するかを指定
          raty(document.querySelector('#read_score_raty_<%= post.id %>'),
              {
                starOn: "<%= asset_path('star-on.png') %>",
                starOff: "<%= asset_path('star-off.png') %>",
                starHalf: "<%= asset_path('star-half.png') %>",
                score: <%= post.comments.average(:read_score).to_f.round(1) %>,
                readOnly: true,
                half: true,
          //星画像の指定などのオプションをここに記述,
              }
          );
        </script>

        <%= '価格の妥当性' %>
        <div id="price_score_raty_<%= post.id %>" data-score="<%= post.comments.average(:price_score).to_f.round(1) %>"></div>
        <script>
          // scriptファイルをどのidの部分に配置するかを指定
          raty(document.querySelector('#price_score_raty_<%= post.id %>'),
              {
                starOn: "<%= asset_path('star-on.png') %>",
                starOff: "<%= asset_path('star-off.png') %>",
                starHalf: "<%= asset_path('star-half.png') %>",
                score: <%= post.comments.average(:price_score).to_f.round(1) %>,
                readOnly: true,
                half: true,
          //星画像の指定などのオプションをここに記述,
              }
          );
        </script>

        <%= '初心者向け度' %>
        <div id="usability_score_raty_<%= post.id %>" data-score="<%= post.comments.average(:usability_score).to_f.round(1) %>"></div>
        <script>
          // scriptファイルをどのidの部分に配置するかを指定
          raty(document.querySelector('#usability_score_raty_<%= post.id %>'),
              {
                starOn: "<%= asset_path('star-on.png') %>",
                starOff: "<%= asset_path('star-off.png') %>",
                starHalf: "<%= asset_path('star-half.png') %>",
                score: <%= post.comments.average(:usability_score).to_f.round(1) %>,
                readOnly: true,
                half: true,
          //星画像の指定などのオプションをここに記述,
              }
          );
        </script>
        <%= link_to "このテキストを評価する", post_path(post.id) %>
    </div>
  </div>

  <div class="row">
    <div class="col mt-5">
      <h4>すべてのコメント<i class="fas fa-mouse">scroll</i></h4>
    </div>
  </div>

  <div class="row scroll">
    <% post.comments.each do |comment| %>
      <div class="comment-box col-3 mt-5">
      <span class="box-title">投稿者名：<%= comment.user.name %></span>
      <p>コメント：</br><%= comment.comment_introduction %></p>

      <%= '総合評価' %>
      <div id="comment_raty_<%= comment.id %>" data-score="<%= comment.total_score %>"></div>
        <script>
        raty(document.querySelector('#comment_raty_<%= comment.id %>'),
            {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              score: <%= comment.total_score %>,
              readOnly: true,
              half: true,
        //星画像の指定などのオプションをここに記述,
            }
        );
        </script>

      <%= '読みやすさ' %>
      <div id="comment_read_score_raty_<%= comment.id %>" data-score="<%= comment.read_score %>"></div>
        <script>
        raty(document.querySelector('#comment_read_score_raty_<%= comment.id %>'),
            {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              score: <%= comment.read_score %>,
              readOnly: true,
              half: true,
        //星画像の指定などのオプションをここに記述,
            }
        );
        </script>

      <%= '価格の妥当性' %>
      <div id="comment_price_score_raty_<%= comment.id %>" data-score="<%= comment.price_score %>"></div>
        <script>
        raty(document.querySelector('#comment_price_score_raty_<%= comment.id %>'),
            {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              score: <%= comment.price_score %>,
              readOnly: true,
              half: true,
        //星画像の指定などのオプションをここに記述,
            }
        );
        </script>

      <%= '初心者向け度' %>
      <div id="comment_usability_score_raty_<%= comment.id %>" data-score="<%= comment.usability_score %>"></div>
        <script>
        raty(document.querySelector('#comment_usability_score_raty_<%= comment.id %>'),
            {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              score: <%= comment.usability_score %>,
              readOnly: true,
              half: true,
        //星画像の指定などのオプションをここに記述,
            }
        );
        </script>
          <p><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></p>
          <p><% if comment.user == current_user %>
          <%= link_to "削除", post_comment_path(post, comment.id), method: :delete %>
          </p>
      <% end %>

      </div>
    <% end %>
  </div>
  <% end %>
</div>