config/routes.rb
Rails.application.routes.draw do
root "homes#top"
get "/homes/about" => "homes#about", as: "about"

devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# scope module: :public do
#   get '/searches/search' => 'searches#search'
#   get '/posts/rank' => 'posts#rank'
#   get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: 'confirm_withdraw'
#   patch '/users/withdraw' => 'users#withdraw'
#   get 'genres/:id/genre_rank' => 'genres#genre_rank', as: 'genre_rank'
#   resources :genres, only: [:show]
#   resources :users, only: [:show, :edit,:update]
#   resource :posts, only: [:new,:create]
#   resources :posts, only: [:show,:index,:destroy,:edit,:update] do
#     resource :favorites, only: [:create, :destroy]
#     resources :comments, only: [:create,:destroy,:new]
#   end
# end

scope module: :public do
  get '/searches/search' => 'searches#search'
  resources :genres, only: [:show] do
    member do 
      get 'genre_rank'
    end
  end
  resources :users, only: [:show,:edit,:update] do
    collection do 
      get 'confirm_withdraw'
      patch 'withdraw'
    end
  end
  resources :posts do
    collection do
      get 'rank'
    end
    resources :comments, only: [:create,:destroy,:new]
    resource :favorites, only: [:create, :destroy]
  end
end

namespace :admin do
  resources :posts, only: [:destroy,:show]
    resources :comments, only: [:destroy]
  resources :users, only: [:show,:index,:edit,:update,:destroy]
  patch '/users/withdraw' => 'users#withdraw'
  get 'users/:id/comment_index' => 'users#comment_index'
  resources :genres, only: [:index, :show, :edit, :create, :update]

end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end


  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def edit
    @admin_edit = User.find(params[:id])
  end

  def update
    @admin_edit = User.find(params[:id])
    if @admin_edit.update(user_params)
      flash[:notice] = 'ユーザー情報の編集成功しました。'
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  def show
    @user_post = User.find(params[:id])
    @posts = @user_post.posts.all
    @user_comment = User.find(params[:id])
    @comments = @user_comment.comments.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted, :encrypted_password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container p-5">
  <div class="row">
    <h1>ユーザー情報編集</h1>
  </div>

  <div class="row mt-2">
    <div class="col-8 mx-auto text-center">
      <%= form_with model: @admin_edit, url: admin_user_path do |f| %>
        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>
        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>
        <div class="field">
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted, "有効", { value: :false, style: "display: inline-block;" } %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_deleted, "退会", { value: :true, style: "display: inline-block;" } %>
        </div>
        <%= f.submit '変更を保存' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container p-5">
  <div class="row">
    <h1>ユーザーリスト</h1>
    <table class='table'>
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>投稿数</th>
          <th>コメント数</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
                <%= user.name %>
            </td>
            <td><%= user.email %></td>
            <td>
                <%= link_to admin_user_path(user.id) do %>
                <%= user.posts.count %>
                <% end %>
            </td>
            <td>
                <%= link_to admin_user_path(user.id) do %>
                <%= user.comments.count %>
                <% end %>
            </td>
            <td><% if user.is_deleted %>
            退会
            <% else %>
            有効
            <% end %>
            </td>
            <td><%= link_to "ユーザー情報編集", edit_admin_user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @users %>
  </div>
</div>

app/views/admin/users/post_index.html.erb
<div class="container p-5">
  <h3><%= @user_post.name %>さんの投稿一覧（全<%= @user_post.posts.count %>件）<i class="fas fa-mouse">scroll</i>
</h3>
  <div class="row scroll">
    <div class="col">
      <table class='table'>
        <thead>
          <tr>
            <th nowrap>投稿日時</th>
            <th nowrap>テキスト名</th>
            <th nowrap>テキスト説明</th>
            <th nowrap>レビュー内容</th>
            <th nowrap>価格</th>
            <th nowrap>コメント数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to admin_post_path(post.id) do %>
                  <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
                <% end %>
              </td>
              <td>
                <%= post.text_name %>
              </td>
              <td>
                <%= truncate(post.introduction, length: 48) do %>
                  (<%= link_to '投稿詳細', admin_post_path(post.id) %>）
                <% end %>
              </td>
              <td>
                <%= truncate(post.review, length: 48) do %>
                  (<%= link_to '投稿詳細', admin_post_path(post.id) %>）
                <% end %>
              </td>
              <td>
                ¥<%= post.price %>
              </td>
              <td>
                <%= post.comments.count %>
              </td>
              <td>
                <%= link_to "削除", admin_post_path(post), method: :delete, data: { confirm: "本当に投稿を削除しますか？" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <h3>コメント一覧（全<%= @user_comment.comments.count %>件）<i class="fas fa-mouse">scroll</i></h3>
  <div class="row scroll">
    <div class="col">
      <table class='table'>
        <thead>
          <tr>
            <th nowrap>投稿日時</th>
            <th nowrap>投稿者名</th>
            <th nowrap>テキスト名</th>
            <th nowrap>コメント内容</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @comments.each do |comment| %>
            <tr>
              <td>
                <%= link_to admin_post_path(comment.post.id) do %>
                <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
                <% end %>
              </td>
              <td>
                <%= comment.post.user.name %>
              </td>
              <td>
                <%= comment.post.text_name %>
              </td>
              <td>
                <%= comment.comment_introduction %>
              </td>
              <td>
                <%= link_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: "本当に投稿を削除しますか？" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container p-5">
  <h3><%= @user_post.name %>さんの投稿一覧（全<%= @user_post.posts.count %>件）<i class="fas fa-mouse">scroll</i>
</h3>
  <div class="row scroll">
    <div class="col">
      <table class='table'>
        <thead>
          <tr>
            <th nowrap>投稿日時</th>
            <th nowrap>テキスト名</th>
            <th nowrap>テキスト説明</th>
            <th nowrap>レビュー内容</th>
            <th nowrap>価格</th>
            <th nowrap>コメント数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to admin_post_path(post.id) do %>
                  <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
                <% end %>
              </td>
              <td>
                <%= post.text_name %>
              </td>
              <td>
                <%= truncate(post.introduction, length: 48) do %>
                  (<%= link_to '投稿詳細', admin_post_path(post.id) %>）
                <% end %>
              </td>
              <td>
                <%= truncate(post.review, length: 48) do %>
                  (<%= link_to '投稿詳細', admin_post_path(post.id) %>）
                <% end %>
              </td>
              <td>
                ¥<%= post.price %>
              </td>
              <td>
                <%= post.comments.count %>
              </td>
              <td>
                <%= link_to "削除", admin_post_path(post), method: :delete, data: { confirm: "本当に投稿を削除しますか？" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <h3>コメント一覧（全<%= @user_comment.comments.count %>件）<i class="fas fa-mouse">scroll</i></h3>
  <div class="row scroll">
    <div class="col">
      <table class='table'>
        <thead>
          <tr>
            <th nowrap>投稿日時</th>
            <th nowrap>投稿者名</th>
            <th nowrap>テキスト名</th>
            <th nowrap>コメント内容</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @comments.each do |comment| %>
            <tr>
              <td>
                <%= link_to admin_post_path(comment.post.id) do %>
                <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
                <% end %>
              </td>
              <td>
                <%= comment.post.user.name %>
              </td>
              <td>
                <%= comment.post.text_name %>
              </td>
              <td>
                <%= comment.comment_introduction %>
              </td>
              <td>
                <%= link_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: "本当に投稿を削除しますか？" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>