config/routes.rb
Rails.application.routes.draw do
root "homes#top"
get "/homes/about" => "homes#about", as: "about"

devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# scope module: :public do
#   get '/searches/search' => 'searches#search'
#   get '/posts/rank' => 'posts#rank'
#   get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: 'confirm_withdraw'
#   patch '/users/withdraw' => 'users#withdraw'
#   get 'genres/:id/genre_rank' => 'genres#genre_rank', as: 'genre_rank'
#   resources :genres, only: [:show]
#   resources :users, only: [:show, :edit,:update]
#   resource :posts, only: [:new,:create]
#   resources :posts, only: [:show,:index,:destroy,:edit,:update] do
#     resource :favorites, only: [:create, :destroy]
#     resources :comments, only: [:create,:destroy,:new]
#   end
# end

scope module: :public do
  get '/searches/search' => 'searches#search'
  resources :genres, only: [:show] do
    member do 
      get 'genre_rank'
    end
  end
  resources :users, only: [:show,:edit,:update] do
    collection do 
      get 'confirm_withdraw'
      patch 'withdraw'
    end
  end
  resources :posts do
    collection do
      get 'rank'
    end
    resources :comments, only: [:create,:destroy,:new]
    resource :favorites, only: [:create, :destroy]
  end
end

namespace :admin do
  resources :posts, only: [:destroy,:show]
    resources :comments, only: [:destroy]
  resources :users, only: [:show,:index,:edit,:update,:destroy]
  patch '/users/withdraw' => 'users#withdraw'
  get 'users/:id/comment_index' => 'users#comment_index'
  resources :genres, only: [:index, :show, :edit, :create, :update]

end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
    <%= stylesheet_link_tag '_header' %>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-body">
    <div class="container">
     <a class="navbar-brand text-dark" href="/">
      <div class="d-flex align-items-center">
        <%= image_tag 'angryaikon.jpg', size: "90x70", class: "mr-2" %>
        <div class="navbar-title">
          <h1>Text</br>番付</h1>
        </div>
      </div>
    </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li><strong>〜管理者ログイン中〜</strong></li>
          <li>
            <%= link_to 'ジャンル追加・編集', admin_genres_path, class: 'nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
          <li>
            <%= link_to 'ユーザーリスト', admin_users_path, class: 'nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
          <li>
            <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
        <% else %>
          <li>
            <strong>〜管理者ログイン画面〜</strong>
          </li>
          <li>
            <%= link_to 'ユーザーログイン', new_user_session_path, class: 'nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_footer.html.erb
<%= stylesheet_link_tag '_footer' %>
<footer>
  <div class='container pt-5'>
    <div class="row">
      <div class="social mx-auto">
        <p>© text番付</p>
        <i class="fab fa-twitter-square"></i>
        <i class="fab fa-instagram-square"></i>
        <i class="fab fa-facebook-square"></i>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
    <%= stylesheet_link_tag '_header' %>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-body">
    <div class="container">
      <a class="navbar-brand text-dark" href="/">
          <div class="d-flex align-items-center">
            <%= image_tag 'angryaikon.jpg', size: "90x70", class: "mr-2" %>
            <div class="navbar-title">
              <h1>Text</br>番付</h1>
            </div>
          </div>
        </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav pl-5">
        <% if user_signed_in? %>
          <% if current_user.email != "guest@example.com" %>
          <li>
            <%= link_to 'テキスト投稿', new_post_path, class: 'nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
          <li>
            <%= link_to 'マイページ', user_path(current_user) , class:'sm nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
          <% end %>
          <li>
            <%= link_to 'ランキング', root_path, class:'sm nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
          <li>
            <%= link_to 'テキスト一覧', posts_path, class:'sm nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
          <li>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'sm ml-1 nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
        <% else %>
          <li>
            <%= link_to 'ランキング', root_path, class: 'nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
          <li>
            <%=  link_to '新規登録', new_user_registration_path, class: 'nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
          <li>
            <%= link_to 'ログイン', new_user_session_path, class: 'nav-link', style: 'color: #dda0dd; font-weight: bold;' %>
          </li>
        <% end %>
        </ul>
      </div>
      <% if user_signed_in? %>
  <div class="search_form">
  <strong>〜ようこそ、<%= current_user.name %>さん〜</strong>

    <%= form_with url: searches_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word, placeholder: "テキストの名前で検索", required: true %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-dark" %>
    <% end %>
  </div>
   <% end %>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Text番付</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/ac6e468438.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if request.fullpath.include? "/admin" %>
      <%= render 'layouts/admin_header' %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>
    <main>
    <%= yield %>
    </main>
        <%= render 'layouts/footer' %>
  </body>
</html>